# Tourism
- The foreign tourists visited the State in 2020 was 3.4 lakh, which is -71.36 per cent lower, as compared to 11.89 lakh in the previous year. The number of foreign tourists who visited Kerala in 2021 upto June was 0.15 lakh. The number of domestic tourist arrivals to Kerala in 2020 was 49,88,972  which is -72.86 per cent lower than the previous year. In 2019, the domestic tourist arrival to the State was 1,83,84,233. The number of domestic tourist arrivals up to June 2021 is 27,60,664.
- The foreign exchange earnings from tourism in 2020 was ₹2799.85 crore and domestic tourist earnings was ₹ 6025.68 crore. In 2019, the foreign exchange earnings and domestic tourist earnings were ₹10271.06 crore and ₹24785.62 crore respectively
- Total earnings including direct and indirect means in 2019 was ₹45010.69 crore, an increase of 24.13 per cent over 2018.  But the total earnings in 2020 was only ₹11,335.96 crore, registering a decline of -74.81 per cent over 2019.

# Scientific Services & Research
- KSCSTE drives the research and development efforts of the State through various scientific programmes focusing science popularisation and promotion, research and development, ecology and environment, technology development and transfer, biotechnology development, school level promotional activities and science programmes for women. The seven R&D centres under the Council carried out research and development activities in specific mandated domains.
- The Institute of Advanced Virology has been virtually inaugurated in October 2020.  The clinical virology and viral diagnostics divisions became operational.  The institute initiated steps for establishing a diagnostic facility for airborne pathogens. Five BSL - II laboratories were made functional. The institute started diagnostic services by giving directions to five medical centers for providing samples to IAV for diagnosis of dengue, chikungunya and ZIKA.
- In 2020-21, a total number of 11191 new cases were registered which was 27.7 per cent lower than previous year.  In 2019-20, the new cases registered were 15,474. Of the new cases registered, 5,322 were male (48 per cent) and 5869 were women (52 per cent).There has been a decrease in the number of new cases registered in RCC. It shows the impact of efforts made by the institution in cancer control activities and improvement of treatment facilities available there.RCC prepared population-based cancer registry in Thiruvananthapuram, Kollam, Alappuzha and Pathanamthitta districts.
