# Transport Sector
## Road Sector
- Development and improvement of roads for a total length of 6437.761 km have been carried out including 3,873.167 km of BM and BC under various Plan schemes. This includes 207.573 km State Highways (118.336 km BM/BC) and 6,230.188 km Major District Roads (3,754.831 km BM/BC)/
- KIIFB accorded ₹1,734.14 crore financial sanction for 21 reaches of Hill Highway.
- KIIFB accorded ₹365.58 crore financial sanction for 55.31 km reaches of Coastal Highway
- In 2020-21, 130 bridges design works completed at an approximate amount of ₹2.1430 crore. Detailed Project Report preparation of 32 road projects with a total length of 755 km was completed.
- The electric two wheeler registration in Kerala as on September, 2021 is 4,742 as against 1,334 in the previous year, showing an increase in (+) 28.13 per cent.
- 7 New Sub RT offices came into force viz: at Varkala, Konni,Pathanapuram, Chadayamangalam, Ramanattukara (Feroke), Payyannur and Kondotty.
- Pilot implementation of Wireless Communication & Allied Infrastructure Network project at Eranakulam inaugurated.
- As on March 31, 2021, motor vehicles with valid registrations number is as on March 31, 2021 is 1.48  crore with newly registered vehicles in 2020-21 being 6,62,979
- Traffic crashes involving two wheelers has decreased from 16,970 (46 per day) in 2019 to 8,533 (23.37 per day) in 2021.
- KSRTC imparted training to 178 Conductors, 156 Drivers and 236 other categories of Employees and implemented Pay Roll Administrative Repository for Kerala (G-Spark)
- Completed solar powered vessel especially the first endeavor in inland Water Transport sector in India, named "ADITYA”.
- 120 pax Vega 2 vessel completed and plying service in Kumarakom – Kottayam route handling 3,200 no. of commuters and tourists.
- Built two water taxi viz. Thejas1 and Thejas 2.
- Built one 100 passenger capacity catamaran boats with modern safety systems.
- The Phase 1A from Petta to SN Junction with a length of 1.8 km with 2 stations at a project cost of `710.93 crore is progressing and expected to be commissioned on March, 2022
- Preparatory works from Kakkanad junction to Infopark express way entrance (2.5km) is in progress and JLN Stadium to Kunnumpuram (4.5km) preparatory works was awarded and expected to complete on December, 2021.
- Inauguration of Water Metro boats with 5 terminals is expected on December, 2021.Water Metro will be fully commissioned by June, 2022 utilizing 25 boats and Terminals
- Administrative Sanction was accorded for starting Land Acquisition process and creating LA units/Cells for Silver Line project (Semi High Speed Rail)
- The revenue earnings of KIAL increased from ₹42.00 crore in 2020-21 to ₹27.49 crore in 2021-22 (up to September, 2021).
- Land acquisition (LA) works in connection with the Thiruvananthapuram Light Metro Rail project, which include construction of flyovers at Sreekaryam, Pattom and Ulloor, is in progress.

## Port Sector
- The total cargo exports from Kerala in 2018 were 138793 tonne and in 2020-21, it is 516155 tonne.
- There is significant rise in the number of inland vessels registered in Kerala over the years. It was 90 during 2017-18 and the number rose to 230 during 2020-21 as against 135 in 2019-20.
- 175 steamers and 133 sailing vessels visited the coast of Kerala during 2020-21 which marks a dip as against 224 steamers and 252 sailing vessels during 2019-20.
 
- Shuchitwa Sagaram is a novel project undertaken by the department in 2017 which aimed to collect garbage from sea bed with the help of fishermen and recycle the same to use in the road works under HED has attracted worldwide attention. The project was first started in Neendakara Fishing Harbour and bagged the best success story award of Marine Biology Association of India in 2018. The Project was recognised by The World Economic Forum and National Geography Magazine.

## Water Transport sector
- Valapattanam to Neeleswaram reach (526.20-590.53 km): Stretch made navigable from Valappattanam to Neeleswaram.
- Constructed boat jetty near KMML, Chavara for handling hazardous materials like sulphuric acid and furnace oil.
- Renovated 7 boat jetties and constructed Champakkulam Jhankar boat jetty in Alappuzha
- A solar/electric powered vessel is planned to be introduced at Calicut on similar line  (Sagararani 3)
- Nefertiti – New Cruise Vessel: KSINCL is ready to launch, a 200 pax sea going day cruise ship named “Nefrititi” registered under Merchant Shipping Act. This will be a luxury vessel suitable for multipurpose activities like meetings, parties etc. besides regular excursions.
- The State Water Department gears up to introduce the first fully solar powered station office at Vaikom and also perocured to purchase more solar boats for replacing old wooden boats in this region, thereby to minimize operating costs and pollution
- The State Water department gears up to procure 5 No’s. of air filled dinghy boats. Construction of double deck passenger cum tourist vessels, especially designed for both normal commuter and tourists of Ashtamudilake in Kollam district is in the finishing stage.
- Commuters have almost abstained from utilizing public transport mode due to Covid-19 pandemic menace. So introducing new ventures like water taxi shall be much dependable to the public. As part of the COVID 19 defense operation, the department rescue boat fruitfully used to get patients to the hospital on time, and also helps the health workers and police to reach out the people in the waterlogged region with their services
